[supervisord]
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
nodaemon=true
user=edge

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf

[program:frankenphp]
command=/usr/local/bin/frankenphp run --config /etc/caddy/Caddyfile
autostart=true
autorestart=true
user=edge
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:valkey]
command=/usr/bin/valkey-server --save "" --dir /tmp --appendonly no --bind 127.0.0.1 --port 6379
autostart=true
autorestart=true
user=edge
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sql-proxy]
command=/usr/local/bin/cloud-sql-proxy --quiet
autostart=true
autorestart=true
user=edge
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
